[build]
  command = "pnpm install --frozen-lockfile=false && pnpm build:client"
  publish = "dist/spa"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express", "cors", "serverless-http"]

# Proxy /api/* to the Netlify function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
