# Generated by Django 5.2.6 on 2025-09-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_id', models.CharField(max_length=10, unique=True)),
                ('fc_rs', models.BooleanField(default=False)),
                ('fc_sig', models.BooleanField(default=False)),
                ('fc_tel', models.BooleanField(default=False)),
                ('open_jobs', models.IntegerField(default=0)),
                ('branding_shortfall', models.IntegerField(default=0)),
                ('mileage_km', models.IntegerField(default=0)),
                ('cleaning_due', models.BooleanField(default=False)),
                ('stabling_penalty', models.IntegerField(default=0)),
            ],
        ),
    ]
